# -*- coding: utf-8 -*-
"""Assignment 11 Supervised ML with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYl1om2o0DQM7Ff5WIG2H5qT1WwotbKA

#Assignment 11: Supervised Machine Learning with Python
Name Ayleen Santander
"""

#Import Necessary Libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

#1.Dataset Selection:
#Load data Titanic
Tit = pd.read_csv('titanic (4).csv')

print(Tit.info())
print(Tit.isnull().sum())

# 2. Clean Age (fill NaN with mean)
Tit['Age'] = Tit['Age'].fillna(round(Tit['Age'].mean())).astype(int)

# 3. Clean Embarked (fill NaN with mode)
Tit['Embarked'] = Tit['Embarked'].fillna(Tit['Embarked'].mode()[0])

Tit.head()

# 4. Clean Ticket (extract numeric part only)
Tit['Ticket'] = Tit['Ticket'].str.extract(r'(\d+)$')
Tit['Ticket'] = pd.to_numeric(Tit['Ticket'], errors='coerce').fillna(0).astype(int)

# 5. Clean Cabin — extract deck letter (A, B, C...), fill missing with 'Unknown'
Tit['Cabin'] = Tit['Cabin'].str[0]
Tit['Cabin'] = Tit['Cabin'].fillna('Unknown')

# 6. Clean Name (remove text in parentheses, optional/cosmetic)
Tit['Name'] = Tit['Name'].str.replace(r'\(.*?\)', '', regex=True).str.strip()

print(f'After cleaning:\n', Tit.isnull().sum())

# 7. Encode categorical columns
le_sex = LabelEncoder()
Tit['Sex'] = le_sex.fit_transform(Tit['Sex'])  # male: 1, female: 0

le_embarked = LabelEncoder()
Tit['Embarked'] = le_embarked.fit_transform(Tit['Embarked'])  # S=2, C=0, Q=1

le_cabin = LabelEncoder()
Tit['Cabin'] = le_cabin.fit_transform(Tit['Cabin'])  # deck letters -> numbers

print(Tit.head())

# 8. Define X and y — predicting Sex from Age, Fare, Cabin
X = Tit[['Age', 'Fare', 'Cabin']]
y = Tit['Sex']

# 9. Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# 10. Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 11. Model training
models = {
    'Logistic Regression': LogisticRegression(),'Random Forest': RandomForestClassifier(),'SVM': SVC()
}

results = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    results[name] = (accuracy, report)

for model_name, (accuracy, report) in results.items():
    print(f"{model_name} Accuracy: {accuracy:.2f}")
    print(report)
