# -*- coding: utf-8 -*-
"""Assignment 9 Time Series Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLRZX7Imbow2mTsf2BGvmu70KaIFVFdC

#Assignment 9: Time Series Analysis
#Name Ayleen Santander

# Part 1: Data Exploration:

#Libraries
"""

#Libraries
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.api import SimpleExpSmoothing
from statsmodels.tsa.holtwinters import SimpleExpSmoothing
from statsmodels.tsa.statespace.sarimax import SARIMAX

"""#1. Load the dataset"""

# Load the dataset
ASS9 = pd.read_csv('dataset.csv', parse_dates=['date'], index_col='date')
print(ASS9.head())

"""#2. Explore the dataset to understand its structure, features, and any missing values."""

#Basic structure
print(ASS9.info())
print('Shape:', ASS9.shape)
print('\nDtypes:', ASS9.dtypes)

# Check for missing an duplicates values
missing = ASS9.isnull().sum()
duplicates = ASS9.duplicated().sum()
print("\nMISSING VALUES:\n", missing[missing > 0])
print("\nDUPLICATE ROWS:", duplicates)

describe = ASS9.describe()
print("\nDESCRIPTIVE STATS:\n", describe)

#Rename no space with '_'
ASS9 = ASS9.rename(columns={'meantemp': 'mean_temp', 'meanpressure': 'mean_pressure'})

ASS9

"""#3. Visualize the time series data to identify trends, seasonality, and other patterns."""

#Visualize the Time Series Data: Plot the original meantemp and wind speed values to identify trends, seasonality, and patterns.
plt.figure(figsize=(6,6))
plt.plot(ASS9['mean_temp'], label='Original mean_temp')
plt.plot(ASS9['wind_speed'], label='Original wind_speed')
plt.title('Mean Temperature and Wind Speed Over Time')
plt.xlabel('Date')
plt.ylabel('Mean Temperature and Wind Speed')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.show()

#Visualize the Time Series Data: Plot the original Humidity and Mean Pressure values to identify trends, seasonality, and patterns.
plt.figure(figsize=(6,6))
plt.plot(ASS9['mean_pressure'], label='Original mean_pressure')
plt.plot(ASS9['humidity'], label='Original humidity')
plt.title('Mean Pressure and Humidity Over Time')
plt.xlabel('Date')
plt.ylabel('Mean Pressure and Humidity')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.show()

#Visualize the Time Series Data: Plot the original Humidity and Mean Temperature values to identify trends, seasonality, and patterns.
plt.figure(figsize=(6,6))
plt.plot(ASS9['mean_temp'], label='Original mean_temp')
plt.plot(ASS9['humidity'], label='Original humidity')
plt.title('Mean Temperature and Humidity Over Time')
plt.xlabel('Date')
plt.ylabel('Mean Temperature and Humidity')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.show()

"""#Part 2 Forecasting with Moving Average (3 M.A):
#1. Implement the moving average (3 M.A) forecasting technique to predict future humidity values.
#2. Calculate the moving average for each time point based on the previous three observations. Visualize the forecasted values along with the original time series data.

#1. Implement the moving average (3 M.A) forecasting technique to predict future humidity values.
"""

# Compute the 3-period moving average
ASS9['3_Moving_Average'] = ASS9['humidity'].rolling(window=3).mean()
print(ASS9[['humidity', '3_Moving_Average']])

#Visualize Moving Average Forecast
plt.figure(figsize=(6,6))
plt.plot(ASS9['humidity'], label='Original')
plt.plot(ASS9['3_Moving_Average'], label='3-Period Moving Average', alpha=0.3)
plt.title('Humidity and 3-Period Moving Average')
plt.xlabel('Date')
plt.ylabel('Humidity')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.show()

"""#2. Calculate the moving average for each time point based on the previous three observations.Visualize the forecasted values along with the original time series data."""

# Compute the 3-period moving average
ASS9['3_Moving_Average'] = ASS9['wind_speed'].rolling(window=3).mean()
print(ASS9[['wind_speed', '3_Moving_Average']].head())

#Visualize Moving Average Forecast
plt.figure(figsize=(6,6))
plt.plot(ASS9['wind_speed'], label='Original')
plt.plot(ASS9['3_Moving_Average'], label='3-Period Moving Average', alpha=0.3)
plt.title('Wind Speed and 3-Period Moving Average')
plt.xlabel('Date')
plt.ylabel('Wind Speed')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.show()

# Compute the 3-period moving average
ASS9['3_Moving_Average'] = ASS9['mean_temp'].rolling(window=3).mean()
print(ASS9[['mean_temp', '3_Moving_Average']])

#Visualize Moving Average Forecast
plt.figure(figsize=(6,6))
plt.plot(ASS9['mean_temp'], label='Original')
plt.plot(ASS9['3_Moving_Average'], label='3-Period Moving Average', alpha=0.3)
plt.title('Mean Temperature and 3-Period Moving Average')
plt.xlabel('Date')
plt.ylabel('Mean Temperature')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.show()

# Compute the 3-period moving average
ASS9['3_Moving_Average'] = ASS9['mean_pressure'].rolling(window=3).mean()
print(ASS9[['mean_pressure', '3_Moving_Average']])

#Visualize Moving Average Forecast
plt.figure(figsize=(6,6))
plt.plot(ASS9['mean_pressure'], label='Original')
plt.plot(ASS9['3_Moving_Average'], label='3-Period Moving Average', alpha=0.3)
plt.title('Mean Pressure and 3-Period Moving Average')
plt.xlabel('Date')
plt.ylabel('Mean Pressure')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.show()

"""#Part 3: Forecasting with Exponential Smoothing:

#1. Apply exponential smoothing to the time series data to forecast future humidity values. 2. Choose an appropriate smoothing parameter (alpha) for exponential smoothing.
"""

# Apply Simple Exponential Smoothing (alpha = 0.3)
alpha = 0.3
model = SimpleExpSmoothing(ASS9['humidity']).fit(smoothing_level=alpha,optimized= False)
ASS9['Exp_Smoothed'] = model.fittedvalues
fitted= model.fittedvalues

#Forecast next 20 periods
forecast_steps =20
forecast = model.forecast(forecast_steps)

#Print the resuls
print(ASS9[['humidity', '3_Moving_Average','Exp_Smoothed']].head())

#Visualize
plt.figure(figsize=(6, 6))
plt.plot(ASS9.index, ASS9['humidity'], label='Actual', color='steelblue')
plt.plot(fitted.index, fitted, label=f'Fitted (α={alpha})', color='orange', linestyle='--')
plt.plot(forecast.index, forecast, label='Forecast', color='green', marker='.')
plt.title('Humidity: Exponential Smoothing Forecast')
plt.xlabel('Date')
plt.ylabel('Humidity (%)')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

"""#3. Generate forecasts using exponential smoothing and visualize the results."""

# Forecast the next X steps ahead in the future, replace X with the number of periods to forecast
X = 20  # Adjust as needed
future_forecast = model.forecast(steps=X)
print(future_forecast.head())

plt.figure(figsize=(6,6))
plt.plot(ASS9['humidity'], label='Original')
plt.plot(ASS9['Exp_Smoothed'], label='Exponential Smoothing Forecast', alpha=0.3, color='Red', linestyle='--')
plt.title('Humidity and Exponential Smoothing Forecast')
plt.xlabel('Date')
plt.ylabel('Humidity')
plt.xticks(rotation=45, ha='right')
plt.grid()
plt.legend()
plt.show()

"""#Improve the model use Arima"""

model = SARIMAX(ASS9['humidity'], order=(1,1,1), seasonal_order=(1,1,1,7))
model_fit = model.fit()

future_forecast = model_fit.forecast(steps=20)
print(future_forecast)

# Plot
plt.figure(figsize=(6,6))
plt.plot(ASS9['humidity'], label='Historical', color='steelblue')
plt.plot(future_forecast, label='Forecast', color='purple', marker='.')
plt.title('Humidity Forecast')
plt.xlabel('Date')
plt.ylabel('Humidity')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.grid(alpha=0.3)
plt.show()