# -*- coding: utf-8 -*-
"""Assignment 22 Parsing JSON Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSa49w5JSN5OBcLbCDKofYtxwrtdXdhA

#1. Save the following JSON data as assignment_data.json:

#2. Read and Parse JSON File
1. Write a Python script to read the assignment_data.json file and parse its content.
"""

import json

#Read the JSON file
with open ('assignment_data.json', 'r') as file:
  data = json.load(file)

#Display the data
print (json.dumps(data, indent = 4))

"""#3. Data Extraction"""

#1.  Extract the names and email addresses of all users.
for users in data ['users']:
  print((f'Name: {users['name']}, Email: {users['email']}'))

#2.  Extract the product names and amounts for all orders.
for user in data['users']:
    for order in user['orders']:
        print(f"Name: {order['product']}, Amount: {order['amount']}")

#3.  Extract the city and state for each user's address
for users in data['users']:
    address = users['address']
    print(f"City: {address['city']}, State: {address['state']}, Zipcode: {address['zipcode']}")

#4. Convert JSON Data into a Tabular Format Using pandas
import pandas as pd
#Convert JSON data to dataframe
df= pd.json_normalize(data['users'])
#Display the dataframe
df

"""4. Data Cleaning"""

#1. Ensure all extracted email addresses are valid (contain "@" and ".")
for users in data['users']:
    email = user['email']
    if '@' not in email or '.' not in email:
        print(f"Invalid email address: {email}")
    else:
      print(f'Valida email address:{email}')

#2. Second options
for users in data['users']:
    email = user['email']
    if '@' in email and '.' in email:
        print(f"Name: {users['name']}, Email: {email} - Valid")
    else:
        print(f"Name: {users['name']}, Email: {email} - Invalid")

#2.Convert order amounts to integers (rounded to the nearest whole number)
for user in data['users']:
    for order in user['orders']:
        if 'amount' in order:
            order['amount'] = round(order['amount'])
            print(f"Name: {order['product']}, Amount: {order['amount']}")

"""#5. Summary Report
1. Generate a summary report that includes:

"""

#2.The total number of users.
Total_number_users= len(data['users'])
print(f'Total number of users: {Total_number_users}')

#3. The total amount spent by each user.
for user in data['users']:
  total = sum(order['amount']for order in user['orders'])
  print(f'Name: {user['name']}, Total amount spent: {total}')

# 4. The total amount spent on each product.
product_total = {}

for user in data['users']:
    for order in user['orders']:
        product = order['product']
        amount = order['amount']
        product_total[product] = product_total.get(product, 0) + amount

for product, total in product_total.items():
  print(f'Product: {product}, Total amount spent: {total}')