# -*- coding: utf-8 -*-
"""Assignment 17 Integrating Data from APIs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Y_otihrX9v8Y7643-I_aNTfBhsPAYio

#Assignment 17: Integrating Data from APIs
#Name Ayleen Santander

#Instructions

Following the guidelines in the lab activity, generate the data frame for these 5 cities:

Texas, USA
Tokyo, Japan
Sydney, Australia
Paris, France
Lagos, Nigeria
"""

#Step 1: Import libraries
import pandas as pd
import requests
from bs4 import BeautifulSoup
import os
import time
from dotenv import load_dotenv
load_dotenv()
from google.colab import userdata
api_key = userdata.get('ASSi17Key')

print(repr(api_key))  # check it's not None before moving on

#Step 2: Get the Api_key and URL
api_key = api_key = userdata.get('ASSi17Key')
url = 'https://api.openweathermap.org/data/2.5/weather'

def get_current_weather(city):
    params = {
        'q': city,
        'appid': api_key,
        'units': 'metric'
    }
    try:
        response = requests.get(url, params=params)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
    except requests.exceptions.RequestException as err:
        print(f"An error occurred: {err}")

# Step 3: Process the JSON Data
city = "Texas"
data = get_current_weather(city)

if data:
    temperature = data['main']['temp']
    humidity = data['main']['humidity']
    print(f"Texas, USA:,Temperature: {temperature}°C")
    print(f"Texas, USA:,Humidity: {humidity}%")
else:
    print("Failed to retrieve weather data.")
# City 2
city_2 = "Tokyo"
data = get_current_weather(city_2)
if data:
    temperature = data['main']['temp']
    humidity = data['main']['humidity']
    print(f"Tokyo, Japan: Temperature: {temperature}°C")
    print(f"Tokyo, Japan: Humidity: {humidity}%")
else:
    print("Failed to retrieve weather data.")

# City 3
city_3 = "Sydney"
data = get_current_weather(city_3)
if data:
    temperature = data['main']['temp']
    humidity = data['main']['humidity']
    print(f"Sydney, Australia: Temperature: {temperature}°C")
    print(f"Sydney, Australia: Humidity: {humidity}%")
else:
    print("Failed to retrieve weather data.")

# City 4
city_4 = "Paris"
data = get_current_weather(city_4)
if data:
    temperature = data['main']['temp']
    humidity = data['main']['humidity']
    print(f"Paris, France: Temperature: {temperature}°C")
    print(f"Paris, France: Humidity: {humidity}%")
else:
    print("Failed to retrieve weather data.")

# City 5
city_5 = "Lagos"
data = get_current_weather(city_5)
if data:
    temperature = data['main']['temp']
    humidity = data['main']['humidity']
    print(f"Lagos, Nigeria: Temperature: {temperature}°C")
    print(f"Lagos, Nigeria: Humidity: {humidity}%")
else:
    print("Failed to retrieve weather data.")

api_key = api_key = userdata.get('ASSi17Key')

cities = [
    {"city": "Houston", "country": "US"}, #represent Texas, USA
    {"city": "Tokyo", "country": "JP"},
    {"city": "Sydney", "country": "AU"},
    {"city": "Paris", "country": "FR"},
    {"city": "Lagos", "country": "NG"}
]

base_url = "http://api.openweathermap.org/data/2.5/weather"
weather_data = []

for c in cities:
    params = {
        "q": f"{c['city']},{c['country']}",
        "appid": api_key,
        "units": "metric"  # Celsius
    }
    response = requests.get(base_url, params=params)
    data = response.json()

    if response.status_code == 200:
        weather_data.append({
            "City": data["name"],
            "Country": data["sys"]["country"],
            "Temperature (°C)": data["main"]["temp"],
            "Feels Like (°C)": data["main"]["feels_like"],
            "Humidity (%)": data["main"]["humidity"],
            "Weather": data["weather"][0]["description"],
            "Wind Speed (m/s)": data["wind"]["speed"]
        })
    else:
        print(f"Error fetching data for {c['city']}: {data.get('message')}")

df = pd.DataFrame(weather_data)
df

##Read JSON files from Postman
import json
import pandas as pd
import glob

#request the json.files
filenames = [
    "houston.json",
    "tokyo.json",
    "sydney.json",
    "paris.json",
    "lagos.json"
]

weather_data = []

for file in filenames:
    with open(file, "r") as f:
        data = json.load(f)

    weather_data.append({
        "City": data["name"],
        "Country": data["sys"]["country"],
        "Temperature (°C)": data["main"]["temp"],
        "Feels Like (°C)": data["main"]["feels_like"],
        "Humidity (%)": data["main"]["humidity"],
        "Weather": data["weather"][0]["description"],
        "Wind Speed (m/s)": data["wind"]["speed"]
    })

df = pd.DataFrame(weather_data)
df