# -*- coding: utf-8 -*-
"""Assignment 21 Parsing CSV Files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLtvB9aHqYkVfLnLpT0znV0W3s8YkM6o

#Assignment 21: Parsing CSV Files
#Name Ayleen Santander

#Part 1:   #1.  Read and Display Data: Write a script to read the CSV file provided at the bottom of the page (assignment_sales_data.csv) and display the data.
"""

#Libraries
import pandas as pd
import csv

#Load the csv file
df = pd.read_csv('assignment_sales_data.csv')
#Check for missing values before cleaning
print(df)

#open the csv file
with open ('assignment_sales_data.csv', mode ='r') as file:
  csv_reader = csv.reader(file)
#Display the data
  for row in csv_reader:
    print(row)

"""#Part 2 :Data Extraction and Cleaning:
1. Calculate total sales.
2. Calculate the average customer age.
3. Handle missing values in the `Customer_Age` and `Customer_Location` columns by filling them with the average age and a placeholder 'Unknown' respectively.

"""

#1. Calculate total sales.
total_sales = df['Sales'].sum()
print("Total Sales:", total_sales)

#Additional Step: Group by product and calculate total sales
product_sales = df.groupby('Product')['Sales'].sum()
print("Total Sales by Product:")
print(product_sales)

#2. Calculate the average customer age.
Average_Customer_Age = df['Customer_Age'].mean()
print("Average Customer Age:")
print(f"{Average_Customer_Age:.2f}")

#Additional Calculate average Age by Sales
Average_Customer_Age = df.groupby('Sales')['Customer_Age'].mean()
print("Average Age by Sales:")
print(Average_Customer_Age.apply(lambda x: f"{x:.2f}"))

#3. Handle missing values in the Customer_Age and Customer_Location columns by filling them with the average age and a placeholder 'Unknown' respectively.
#Check for missing values before cleaning
print('Missing valus before cleaning:')
print (df.isnull().sum())

#Apply fillna for missing values for customer_age, Customer_locationn and additional Payment_Method

df.fillna({'Customer_Age': df['Customer_Age'].mean(), 'Customer_Location': 'Unknown', 'Payment_Method': 'Unknown'}, inplace = True)

#Correct formatting issues (example: standardize customer location names)
df['Customer_Location']= df ['Customer_Location'].str.strip().str.title ()
#verify missing values are handled
print('\nMissing values after cleaning:')
print(df.isnull().sum())

"""#Part 3: Advanced Data Analysis with Pandas:
1. Group data by product and calculate total sales per product.
2. Identify and list all unique payment methods used.
"""

#1. Group data by product and calculate total sales per product.
product_sales = df.groupby('Product')['Sales'].sum()
print("Total Sales by Product:")
print(product_sales)

#2. Identify and list all unique payment methods used.
payment_method = df.groupby(['Product', 'Payment_Method'])['Sales'].sum()
print(payment_method)

"""#Part 4: Generate a Summary Report:
Create a summary report in a text file or Word document that includes:
1. Total sales
2. Average customer age
3. Total sales by product
4. List of unique payment methods
"""

#1. Total Sales
total_sales = df['Sales'].sum()
print("Total Sales:", total_sales)

#2. The average customer age.
Average_Customer_Age = df['Customer_Age'].mean()
print("Average Customer Age:")
print(f"{Average_Customer_Age:.2f}")

#3. Total sales by product
product_sales = df.groupby('Product')['Sales'].sum()
print("Total Sales by Product:")
print(product_sales)

#4. List all unique payment methods used.
payment_method = df.groupby(['Product', 'Payment_Method'])['Sales'].sum()
print(payment_method)